### ISSUE TITLE
Support for count and reverse in get_slice and get_count functions

### ISSUE THREAD

**Issue by jcbf** [gslin/cassandra-lite-perl#4]
This patch will do the magic :p

It can be called like this:
my $res1 = $c->get_slice($columnFamily, $key, {consistency_level => 'ALL',count => 20, reversed => 1});

--- /home/jcbf/lib/Cassandra/Lite.pm    2011-04-18 16:22:12.000000000 +0100
+++ /usr/local/share/perl/5.10.1/Cassandra/Lite.pm  2011-06-03 13:19:40.016239520 +0100
@@ -185,7 +185,7 @@
     # TODO: cache this
     my $columnParent = Cassandra::ColumnParent->new({column_family => $columnFamily});
-    my $sliceRange = Cassandra::SliceRange->new;
-    my $sliceRange = Cassandra::SliceRange->new($opt);
   if (defined $opt->{range}) {
       $sliceRange->{start} = $opt->{range}->[0] // '';
       $sliceRange->{finish} = $opt->{range}->[1] // '';
  @@ -215,7 +215,7 @@
   # TODO: cache this
   my $columnParent = Cassandra::ColumnParent->new({column_family => $columnFamily});
-    my $sliceRange = Cassandra::SliceRange->new;
-    my $sliceRange = Cassandra::SliceRange->new($opt);
   if (defined $opt->{range}) {
       $sliceRange->{start} = $opt->{range}->[0] // '';
       $sliceRange->{finish} = $opt->{range}->[1] // '';

**Comment by gslin** [comment]
Looks fine, I'll check it later...

**Comment by jcbf** [comment]
Hi!
I just implemented multiget_count,multiget_slice and get_range_slices (welll , largely based on previous methods). Do you want me to send you the patch via email ?

**Comment by gslin** [comment]
You can send me via pull-request :-)
