### ISSUE TITLE
bug in insert?

### ISSUE THREAD

**Issue by erantapaa** [gslin/cassandra-lite-perl#5]
In the insert method, shouldn't $self->client->insert(...) be inside the while loop?

**Comment by jcbf** [comment]
why is that ? for multiple inserts you should use batch_mutate ( API level ) or the batch_insert wich is supported in the patch I recently put on "pull request"

**Comment by erantapaa** [comment]
Ok - so %$opt should only have one key. 

So here's a question... is this a legal way to call ->insert?

```
$cl->insert($column_family, $key, { foo => 'bar', timestamp => 123456 })
```

If so, how can you be assured that $column->{name} will be set to 'foo'? If each %$opt returns the keys in the order 'foo', 'timestamp', then at the time of the call to ->client->insert $column->{name} will be 'timestamp'. Or maybe I don't understand how ->insert should be used.

**Comment by jcbf** [comment]
I think we are both right.

According to module examples, you should be able to insert multiple columns. In that case, there is a bug.
According to [Cassandra API](http://wiki.apache.org/cassandra/API) doc 
**insert**

insert(key, column_path, column, consistency_level)
Insert a Column consisting of (name, value, timestamp) at the given column_path.column_family and optional column_path.super_column. Note that a SuperColumn cannot directly contain binary values -- it can only contain sub-Columns. Only one sub-Column may be inserted at a time, as well.

I will send a patch to fix the behavior of insert and support what's on the POD.

**Comment by jcbf** [comment]
It's here:
https://github.com/jcbf/cassandra-lite-perl/commit/b212d63aaf05f64402792c422cebd1049daab2d3

**Comment by gslin** [comment]
I've cherry-pick this patch, thanks!
